import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { FaLinkedin, FaGithub } from "react-icons/fa";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "HotelEase",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <header className="fixed top-0 left-0 w-full h-[80px] flex items-center justify-between px-8 bg-[#59443F] text-[#F2E0D0] z-50 shadow-md">
          <Link href={'/'} className="text-3xl font-bold tracking-wide">HotelEase</Link>
          <nav className="flex gap-6 text-lg">
            <Link href={'/reservas'} className="hover:text-[#A69581] cursor-pointer transition">Reservas</Link>
            <Link href={'/sobre'} className="hover:text-[#A69581] cursor-pointer transition">Sobre</Link>
          </nav>
        </header>

        <main
          className="flex justify-center flex-1 bg-fixed bg-cover bg-center bg-no-repeat mt-[80px] mx-2"
          style={{
            backgroundImage: "url('/fundo-hotel1.jpg')",
          }}
        >
          {children}
        </main>

        <footer className="flex items-center justify-between px-8 py-3 bg-[#59443F] text-[#F2E0D0]">
          <p className="text-lg font-bold tracking-wide">Ariel Santos</p>

          <nav className="flex gap-6 text-lg">
            <a
              href="https://www.linkedin.com/in/ariel-santos-souza-998b8b31a"
              target="_blank"
              rel="noopener noreferrer"
              className="hover:text-[#A69581] transition-transform transform hover:scale-110"
            >
              <FaLinkedin size={24} />
            </a>
            <a
              href="https://github.com/Arielsnts"
              target="_blank"
              rel="noopener noreferrer"
              className="hover:text-[#A69581] transition-transform transform hover:scale-110"
            >
              <FaGithub size={24} />
            </a>
          </nav>
        </footer>
      </body>
    </html>
  );
}
